### PR TITLE
Reorder handlers

### PR DESCRIPTION
**Pull request by lewg**
I believe ansible runs handlers in the order they're defined in the `handlers/main.yml`, and the systemd reload should happen before the consul restart.

### CODE REVIEW

**Comment by lewg** [comment]
Any feedback?

**Comment by savagegus** [comment]
Is there a reason to reorder them?

**Comment by lewg** [comment]
The way it is now systemd will reload consul and THEN update the config, so your config isn't applied.

**Comment by savagegus** [comment]
It is my understanding that handlers are not run in order but are triggered by tasks. See the handler section here: http://docs.ansible.com/ansible/playbooks_intro.html
Someone correct me if I'm wrong.

**Comment by lewg** [comment]
Indeed, from that page: `Notify handlers are always run in the same order they are defined, not in the order listed in the notify-statement.`  

So, your playbook runs, collecting handlers along the way. Then, at the end, it fires all the collected notifications in the order they were defined.

**Comment by lewg** [comment]
Switched to #149.

**Pull request closed without merging**
