### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sgirones**
The current ansible-galaxy command installs an old role

### CODE REVIEW

**Comment by aairey** [comment]
The real problem here is that the Ansible galaxy [role](https://galaxy.ansible.com/savagegus/consul/) is not updated correctly.
Maybe due to not updating the metadata?

**Comment by sgirones** [comment]
I assumed the role was renamed, because https://galaxy.ansible.com/savagegus/ansible-consul/ is being updated correctly

**Comment by aairey** [comment]
True, could be. Only @savagegus would know, I guess :)

**Comment by aairey** [comment]
I don't use `arm` (ansible role manager) but maybe that example should be adjusted too :)

**Pull request merged**
